/* @jsxRuntime classic */

import "./globals.css";
import React from "react";
import { Navibar } from "../components/navbar";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";

export const metadata = {
  title: 'Plane shop',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ShoppingCartProvider>
          <Navibar/>
          {children}
        </ShoppingCartProvider>
      </body>
    </html>
  )
}
